---
default_stages: [pre-commit]
repos:
    # Black for Python formatting
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black

    # Prettier for HTML, CSS, JS formatting
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
          - id: prettier
            types_or: [javascript, css, html]
            additional_dependencies:
                - prettier@3.0.0

    # Commitlint for commit message linting
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.22.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]

    # Markdownlint for markdown linting
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.44.0
      hooks:
          - id: markdownlint
            name: markdownlint
            entry: markdownlint
            language: node
            types: [markdown]
